import turtle
t = turtle.Turtle()
t.shape('turtle')

side = 100
angle = 90

t. forward(side)
t. right(angle)
t. forward(side)
t. forward(side)
t. right(angle)
t. forward(side)
t. forward(side)
t. right(angle)
t. forward(side)
t. forward(side)
t. right(angle)
t. forward(side)
t. right(angle)
t. forward(side)
t. forward(side)
t. right(angle)
t. forward(side)
t. right(angle)
t. forward(side)
t. right(angle)
t. forward(side)
t. forward(side)
t. right(angle)
t. right(angle)
t. forward(side)
